allowBuilds:
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: false
  protobufjs: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
